# Generated by Django 4.2.4 on 2023-08-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='endpoints',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='app_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cloudprofile_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
