# Generated by Django 4.2.4 on 2023-08-08 06:10

from django.db import migrations, models
import django_extensions.db.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, primary_key=True, serialize=False, unique=True)),
                ('application_name', models.CharField(max_length=64, null=True)),
                ('application_type', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('endpoints', jsonfield.fields.JSONField(null=True)),
                ('status', models.TextField(null=True)),
                ('project_id', models.TextField(null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('owner', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('cloudprofile_id', models.IntegerField(null=True)),
                ('profile_name', models.TextField(null=True)),
                ('app_count', models.IntegerField(default=0, null=True)),
                ('instances', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
